[bot]
adapters = ["alicebot.adapter.mirai", "alicebot.adapter.apscheduler"]
plugin_dirs = ["plugins"]

[adapter.mirai]
adapter_type = "ws"
verify_key = "1234567890"
qq = 3809536421
port = 23663

[adapter.apscheduler]
scheduler_config = { "apscheduler.timezone" = "Asia/Shanghai" , 'apscheduler.job_defaults.misfire_grace_time' = '10'}